name: Wiki

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.wiki_key }}
          known_hosts: ${{ secrets.wiki_hosts }}
      - name: Update the wiki
        run: |
          git --version
          git push --force git@github.com:SuperTux/supertux.wiki.git HEAD:master
